/**
 * The default seed: the client's masters, no transactions.
 *
 * `npm run db:reset` runs this after `prisma migrate reset`, so a reset produces a clean,
 * ready-to-use tool rather than refilling it with the historical demo data. The old demo
 * chain is still available as `npm run db:reset:demo`.
 *
 * The baseline SQL is regenerated by `npm run db:snapshot` from a live wiped database, so
 * this file never has to be kept in sync with the schema by hand.
 */
import "dotenv/config";
import { readFileSync } from "node:fs";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL ?? "file:./dev.db" });
const db = new PrismaClient({ adapter });

async function main() {
  const sql = readFileSync("prisma/seed_baseline.sql", "utf8");
  const statements = sql
    .split("\n")
    .filter((l) => l.startsWith("INSERT INTO "))
    .map((l) => l.replace(/;\s*$/, ""));

  if (statements.length === 0) throw new Error("prisma/seed_baseline.sql has no INSERT statements");

  // The file is emitted parents-first, so plain sequential execution satisfies every FK.
  await db.$transaction(async (tx) => {
    for (const s of statements) await tx.$executeRawUnsafe(s);
  });

  const [c] = await db.$queryRawUnsafe<Record<string, bigint | number>[]>(
    `SELECT (SELECT COUNT(*) FROM "User") u, (SELECT COUNT(*) FROM "Product") p,
            (SELECT COUNT(*) FROM "Fabric") f, (SELECT COUNT(*) FROM "TrimItem") t,
            (SELECT COUNT(*) FROM "Vendor") v, (SELECT COUNT(*) FROM "Lookup") l`
  );
  console.log(
    `Baseline seeded: ${c.u} users, ${c.p} products, ${c.f} fabrics, ${c.t} trims, ` +
      `${c.v} vendors, ${c.l} lookups. No job cards, orders or stock — start fresh.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
