/**
 * Snapshot the current master data as the baseline `npm run db:reset` rebuilds from.
 *
 * Run this AFTER `npm run db:wipe`. It writes prisma/seed_baseline.sql — plain INSERT
 * statements, ids and all — so a reset reproduces the exact clean state the client
 * starts from rather than a hand-written approximation that can drift from it.
 *
 * Rows are emitted straight from SQLite with no type coercion (dates are already ISO
 * text, booleans already 0/1), so the round trip is byte-faithful.
 *
 *   npm run db:snapshot
 */
import "dotenv/config";
import { writeFileSync } from "node:fs";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL ?? "file:./dev.db" });
const db = new PrismaClient({ adapter });

/**
 * Parents before children — this is the insert order too. Lookup is self-referencing
 * (SUB_CATEGORY rows point at a HEAD_CATEGORY row), so it is ordered heads-first.
 */
const TABLES: { name: string; orderBy: string }[] = [
  { name: "User", orderBy: "id" },
  { name: "Colour", orderBy: "id" },
  { name: "Vendor", orderBy: "id" },
  { name: "CuttingMaster", orderBy: "id" },
  { name: "Supplier", orderBy: "id" },
  { name: "Lookup", orderBy: '"parentId" IS NOT NULL, id' },
  { name: "Fabric", orderBy: "id" },
  { name: "FabricColor", orderBy: "id" },
  { name: "TrimItem", orderBy: "id" },
  { name: "Product", orderBy: "id" },
  { name: "ProductColor", orderBy: "id" },
  { name: "Bom", orderBy: "id" },
  { name: "BomLine", orderBy: "id" },
  { name: "ImageAsset", orderBy: "id" },
];

const lit = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "bigint") return String(v);
  if (typeof v === "boolean") return v ? "1" : "0";
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

async function main() {
  const out: string[] = [
    "-- Baseline master data for `npm run db:reset`.",
    "-- Generated by scripts/snapshot-baseline.ts — do not hand-edit.",
    "-- Transactions are deliberately absent: a reset yields a clean, ready-to-use tool.",
    "",
  ];
  let total = 0;

  for (const { name, orderBy } of TABLES) {
    const rows = await db.$queryRawUnsafe<Record<string, unknown>[]>(
      `SELECT * FROM "${name}" ORDER BY ${orderBy}`
    );
    out.push(`-- ${name}: ${rows.length}`);
    for (const r of rows) {
      const cols = Object.keys(r).map((c) => `"${c}"`).join(", ");
      const vals = Object.values(r).map(lit).join(", ");
      out.push(`INSERT INTO "${name}" (${cols}) VALUES (${vals});`);
    }
    out.push("");
    total += rows.length;
    console.log(`  ${name.padEnd(16)} ${rows.length}`);
  }

  writeFileSync("prisma/seed_baseline.sql", out.join("\n"));
  console.log(`\nWrote prisma/seed_baseline.sql — ${total} rows across ${TABLES.length} tables.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
